### ISSUE TITLE
Umbrella issue for docs cleanup

### ISSUE THREAD

**Issue by kevin-bates** [gateway-experiments/gateway_provisioners#43]
The docs are in place and building, but still contain information that is only relative to Enterprise Gateway and really needs a series of passes (per https://github.com/gateway-experiments/gateway_provisioners/issues/43#issuecomment-1414509075 below).  As a result, I've decided to turn this issue into an _umbrella issue_ so that this work can be more easily distributed (as necessary).

- [x] [Cleanup Users Guide](https://github.com/gateway-experiments/gateway_provisioners/issues/50)
- [x] [Cleanup Operators Guide](https://github.com/gateway-experiments/gateway_provisioners/issues/51)
- [x] [Cleanup Developers Guide](https://github.com/gateway-experiments/gateway_provisioners/issues/52)
- [x] [Cleanup Contributors Guide](https://github.com/gateway-experiments/gateway_provisioners/issues/53)
- [x] [Cleanup Other section](https://github.com/gateway-experiments/gateway_provisioners/issues/54)

**Comment by kevin-bates** [comment]
Here are some quick (and **rough**) notes I took in making a pass through the document's Table of Contents.  The items prefixed with `'x'` represent areas that require significant changes, while those prefixed with `'-'` indicate that minor changes are required.  Those not prefixed seem to be okay, but should not be precluded from additional checks.
```
Table of Contents
xUsers
x    Connecting the server to Enterprise Gateway (make general and explain local use vs remote use)
-    Kernel Environment Variables (still some EG refs)
Operators
x    Deploying Gateway Provisioners
-    Configuring Gateway Provisioners
Developers
    Implementing a remote provisioner
-    Implementing a kernel launcher (links to EG, add some python code examples)
x    Implementing a kernel specification (introduce tooling, )
x    Custom Kernel Images (add note that EG kernel images should be compatible, reference the docker-stacks base image and no others, and the kernel-image Dockerfile, should code-snippets for injecting )
-    API Docs (fixup section descriptions - probably from top of file help string, try to remove TrackKernelOnHost, KernelChannel, gp_launch_kernel, why is RemoteProvisionerBase listed twice?)
xContributors (still EG)
    Contributing to Gateway Provisioners
x    System Architecture (Update hierarchy image, EG refs in {Kubernetes,DockerSwarm}Provisioner, Remove CustomResourceProv, Update Launchers example, )
x    Docker Images - reiterate EG b/c, remove eg-image refs, replace with Dockerfile examples?
    Development Workflow
x    Sequence Diagrams (Generalize EG to Gateway Server)
    API Docs - linked to dev (ok)
X    Debugging Jupyter Enterprise Gateway (update images)
Other
x    Troubleshooting Guide (EG refs, remove old stale stuff)
x    Related Resources (EG ref)
```

**Comment by kevin-bates** [comment]
Tasks have been completed and docs have reached a _minimally viable_ state - closing.
